### ISSUE TITLE
Add login/password handling

### ISSUE THREAD

**Issue by QuentinCG** [Oliv4945/jarvis-mqtt#10]
MQTT brokers may be protected by login/password (to allow only some users to publish/subscribe). 

Using `username_pw_set()` function (not used by default) would be a good idea to have a FULLY protected "Jarvis <-> MQTT broker" connexion.

I can implement this quite easily.

Note: This is not related with SSL handling.

**Comment by Oliv4945** [comment]
Yes, a part of securing I want to add when #9 will be done.

Edit: Not related to SSL but `login:password` is useless in plain text

**Comment by QuentinCG** [comment]
> Not related to SSL but login:password is useless in plain text

I know (it would even be a bad idea).
But it is not related to the #9 (since you can have a broker with/without SSL and with/without login/password).

**Comment by Oliv4945** [comment]
@QuentinCG : Done, if you want to try before I publish the plugin

**Comment by QuentinCG** [comment]
@Oliv4945 I tested it. It works very well :)
Good job!
