### ISSUE TITLE
Help needed in Installation

### ISSUE THREAD

**Issue by ghost** [Oliv4945/jarvis-mqtt#12]
hey first of all thank you for this plugin,
I was thinking on creating similar plugin as I couldn't find this in the jarvis store at openjarvis.com website. Later I found this plugin but couldn't install.

I'm very much new to jarvis so I'm finding difficulty in installing jarvis -mqtt on my own.
The problem according to me, starts from the installation part itself.
It ask for username and password of github, even though I provide my username and pwd. It gives me the following error.
pi@MQTTSVR:~/jarvis $  ./jarvis.sh -p https://github.com/Oliv4945/jarvis-mqtt.gitCloning into 'jarvis-mqtt.git'...
Username for 'https://github.com':
Password for 'https://github.com':

remote: Repository not found.
fatal: Authentication failed for 'https://github.com/Oliv4945/jarvis-mqtt.git.git/'
ERROR: An error has occured
Press [Enter] to continue

I don't know which user and pwd as to be used and I even tried leaving them both blank but it resulted in same error
Please help with this, Thank you

**Comment by QuentinCG** [comment]
Please try with this command:
`./jarvis.sh -p https://github.com/Oliv4945/jarvis-mqtt`


@Oliv4945 Il serait peut être bien de le mettre dans le store? (Le plugin est finalisé, non?)

**Comment by ghost** [comment]
Thank you very much, It is now installed.
Will try this plugin and then report you.

**Comment by ghost** [comment]
Hey hi,

Can you please share the commands code (if you have used in you're jarvis).
I'm in trouble in configuring jarvis with the mqtt. It'll very useful for me, if you share all the coding part you used to configure.

Thank You

**Comment by QuentinCG** [comment]
Hey ;)
Check this out: https://github.com/Oliv4945/jarvis-mqtt/issues/13

**Comment by ghost** [comment]
I did thank you,

**Comment by ghost** [comment]
Hey hi,
the jarvis-mqtt plugin is working awesome as expected, why don't you put it in store?
So other users can utilize it. @Oliv4945 

hey @QuentinCG Please do share me one of your mqtt plugin's example just wanna have idea about how you're using it. Thanks

**Comment by QuentinCG** [comment]
@Oliv4945 I agree with @arjun312.
We should also incorporate a kind of "how to start with basic set-up" like I did in #13 to make this plugin more accessible to users.

@arjun312 I don't have any project related to this plugin for now. I kind of stopped working on Jarvis those past 6 months but will continue when I'll return to my country :smile:
If the current elements sent by the plugin to the channel are not enough for you, you could try to check the python file and edit it for your need by adding a channel? (Check the commits, they are quite clean)
