### ISSUE TITLE
need a sample

### ISSUE THREAD

**Issue by ghost** [Oliv4945/jarvis-mqtt#13]
hey everyone,

Please if there are any samples I can refer to, please share it here. So people like me with no much knowledge in coding, can alter it to their need.
I've tried on my own but it didn't help me out. Please a little help is appreciated
Thank you

**Comment by QuentinCG** [comment]
During the installation, allow the program to install the defaut MQTT broker.

In https://github.com/Oliv4945/jarvis-mqtt/blob/master/config.sh
You should have a file containing this:
```
jv_pg_mqtt_server="localhost"
jv_pg_mqtt_launch_broker=true
jv_pg_mqtt_port=1883
jv_pg_mqtt_topic="/Jarvis"

# Only if you want to control your Jarvis with a Windows/Android app:
jv_pg_mqtt_subscribe_execute="$jv_pg_mqtt_topic/execute"
jv_pg_mqtt_subscribe_say="$jv_pg_mqtt_topic/say"
```

Once all of this is done, launch Jarvis.
You should then:
 - Install an app (MQTT client) in your [computer (Mac/Windows)](http://mqttfx.jensd.de/index.php/download) or in your [android device](https://play.google.com/store/apps/details?id=at.tripwire.mqtt.client&hl=en) or in any other device
 - In this app (MQTT client), try to connect to the MQTT broker launched by the plugin (IP address of your Raspberry Pi, port 1883, no SSL). Your IP address can be found with command `sudo ifconfig` (something like 192.168.x.x)
 - Subscribe to channel '/Jarvis/said' (you'll see all messages sent by Jarvis there)
 - Subscribe to channel '/Jarvis/events' (you'll see all events done by Jarvis there)
 - Send a message in channel 'Jarvis/say' to make Jarvis say something (example: "Hello World")
 - Send a message in channel 'Jarvis/execute' to make Jarvis execute something (example: "Light on")

**Comment by ghost** [comment]
Thank You man @QuentinCG  , You're helping me a lot, thank you so much. I'm trying to combine node-red and mqtt once I'm successful I'll let you know.

**Comment by ghost** [comment]
hey @QuentinCG  how to send payload from jarvis to clients?
Like for instance I need to send "1" as payload from jarvis to my mqtt client. How can I achieve that?
i.e,,, I say to jarvis "lights on" it sends the payload "1" to my mqtt client and receives the response.

Thank you
