### ISSUE TITLE
Install MQTT server and launch it if requested

### ISSUE THREAD

**Issue by QuentinCG** [Oliv4945/jarvis-mqtt#5]
Why not add a MQTT server (disabled by default). This is more an improvement than a problem:

in install.sh:
`sudo apt-get install -y mosquitto`

in config.sh:
`jv_pg_mqtt_server=false`

in startup function:
`$jv_pg_mqtt_server && nohup mosquitto -p $jv_pg_mqtt_port &`

I can do a pull request if assigned to me.
Cheers,
Quentin

**Comment by Oliv4945** [comment]
Hi Quentin, I prefer to avoid : if user need Mosquitto only for Jarvis...he does not need it :p

It would be nice if you have a use case to let me understand :-)
Moreover it would be better to use whiptail to let user choose to install it or not.

**Comment by QuentinCG** [comment]
I imagine fox example using an android app and desktop widgets to control Jarvis.

Since MQTT is quite a common protocol, a lot of apps are available and permits to do fancy stuff.
I'm pretty sure most of Jarvis users don't know about MQTT and don't want to care about creating a MQTT server...

It would be then quite easy to integrate this plugin with android/apple apps without worrying about how it works ;)

>  Moreover it would be better to use whiptail to let user choose to install it or not.

True, I was just explaining my point with a fast example ;)

**Comment by QuentinCG** [comment]
I added a pull request for this "improvement".

**Comment by QuentinCG** [comment]
Done with https://github.com/Oliv4945/jarvis-mqtt/pull/7
