### ISSUE TITLE
Add a topic to execute a command (-x)

### ISSUE THREAD

**Issue by QuentinCG** [Oliv4945/jarvis-mqtt#6]
Hey, 

There is a topic to ask Jarvis to say something (-s). It would be nice to add a topic to ask Jarvis to execute a function (-x).

I can do it if assigned to me.

Cheers,
Quentin

**Comment by Oliv4945** [comment]
> There is a topic to ask Jarvis to say something (-s). It would be nice to add a topic to ask Jarvis to execute a function (-x).
Why not, do you have a use case ? I'll do it or you can propose a PR if you want.

**Comment by QuentinCG** [comment]
Using "execute command" would provide user possibility to ask jarvis to do request FROM any MQTT client instead of doing it by the voice ! It would make MQTT client less passive (they could interact with Jarvis instead of just seeing what he is doing and asking him to speak) ;)

For example:
 1) Sending message to Jarvis: /Jarvis/execute "Light on the living-room" 
 2) Jarvis executes the command (lighting on the living room)
 3) Jarvis publishes the result in /Jarvis/said "Living-room light is on."

All of those stuff could be done directly from an android app / widget / button ! (easy to configure in local, great result).

**Comment by QuentinCG** [comment]
In other words, it's like jarvis-api but with numerous apps available to communicate with Jarvis ;-)

**Comment by QuentinCG** [comment]
I added a pull request for this "improvement".

**Comment by Oliv4945** [comment]
Thank you for the pull request, I merged it.

>In other words, it's like jarvis-api

That was what I was wondering, and I didn't want to add another "security hole". So for now [I disabled it by default](https://github.com/Oliv4945/jarvis-mqtt/commit/09ab1a98ff33d8ae4b9ba4e64a288d58c4fe4aac), but user can uncomment the topic in config.h to enable it.
