### ISSUE TITLE
Add SLL handling

### ISSUE THREAD

**Issue by QuentinCG** [Oliv4945/jarvis-mqtt#9]
Following comment https://github.com/alexylem/jarvis-api/commit/8f4040a3a883bf3df03abd33af338394a82dc4ef#commitcomment-22156117, it would be nice to integrate SSL for this plugin.

Here is the needed paho.mqtt python function to integrate SSL: https://pypi.python.org/pypi/paho-mqtt/1.2#tls-set

I think it is better to disable this feature by default since it is easier for new user to test this plugin with a basic broker and then use "expert config" later.

Note: Use example should be added in README.md or in comment in the config.sh file ? (with a secured and non-secured public broker)

**Comment by QuentinCG** [comment]
Simple example of SSL with MQTT (I think it is also better to specify the certificate version and stuff like this.... to handle more cases):


```
import paho.mqtt.client as paho

def on_message(clnt, userdata, msg):
    print(msg.topic+" "+str(msg.payload))

mqttc = paho.Client()
mqttc.on_message = on_message
mqttc.tls_set("mosquitto.org.crt") # http://test.mosquitto.org/ssl/mosquitto.org.crt
mqttc.connect("test.mosquitto.org", 8883)
mqttc.subscribe("bbc/#")
mqttc.loop_forever()
```

**Comment by Oliv4945** [comment]
Tank you @QuentinCG , it is the next step I want to do.  
Nevertheless there is a way to avoid having a local "*.crt" file, at least in node.js. So it should be available in Python too.
From [the docs](https://pypi.python.org/pypi/paho-mqtt/1.1) it seems that configuring `ca_certs` parameter to `Let's Encrypt Authority X3` or whatever used authority is enough. I will do some tests

**Comment by QuentinCG** [comment]
Good luck ;)

Certificates is a nightmare...
I'll have a look too.

**Comment by QuentinCG** [comment]
This could help: http://stackoverflow.com/questions/16903528/how-to-get-response-ssl-certificate-from-requests-in-python

**Comment by Oliv4945** [comment]
I just tried, it is not difficult. As I thought, you just have to give a path to approved certificated authorities.
If you do not have this file "apt-get install ca-certificates".

Let me test a bit more then I will push the changes

```
tls_dict = { 'ca_certs':"/etc/ssl/certs/ca-certificates.crt", 'tls_version':ssl.PROTOCOL_TLSv1_2}
publish.single(topic=args.topic, payload=args.message.decode('utf-8'), hostname=args.server, port=args.port, tls=tls_dict)
```

**Comment by QuentinCG** [comment]
Wow ! this is perfect. Strange I never saw this before.

`apt-get install ca-certificates` should maybe be added to the install? (without asking)

**Comment by Oliv4945** [comment]
> Wow ! this is perfect. Strange I never saw this before.

Is was not in the documentation ;-) , but [code ](https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/publish.py#L186)documentation is good. Also, it helped me to look in the documentation of python's ssl module.

> apt-get install ca-certificates should maybe be added to the install? (without asking)

It will be, but let me check that I did no broke anything before pushing it

**Comment by Oliv4945** [comment]
@QuentinCG : It should be ok now, could you please have a look ?
For future reference, here is the mosquitto.conf I used for SSL:
```
# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /var/run/mosquitto_ssl.pid

persistence true
persistence_location /var/lib/mosquitto_ssl/

log_dest file mosquitto_ssl.log

port 1884

cafile /etc/ssl/certs/DST_Root_CA_X3.pem
certfile /home/blabla/fullchain.pem
keyfile /home/blabla/privkey.pem
```

**Comment by QuentinCG** [comment]
Works perfectly with valid certificate but fails with self-signed certificates. For me it's more than enough :)
Good job!

If you really want to allow self signed certificates:
 - Subscribe: Add `mqttc.tls_insecure_set(True)`
 - Publish: More complicate since `publish.single()` does not handle this...

Note: I used an exernal server using Let's Encrypt certificate (valid certificate) + domain name + login/password.

**Comment by Oliv4945** [comment]
Thank  you for the tests !

I thought about that and I prefer to avoid it for now because, if people are concerned enough to use SSL, they will find a way to use Let's Encrypt. Of course if too many people ask I will reconsider it.

**Comment by QuentinCG** [comment]
Seems legit ;) (I just wanted to give a feedback from what I saw with your plugin)
